#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."
docker build -f Dockerfile.build -t build-etcd-operator .

docker run build-etcd-operator |
  docker build -f Dockerfile.release -t etcd-operator -
